package de.dal33t.powerfolder.d2d;

public enum NodeState {

    LISTEN,
    OPEN_IDENTITY_REPLY_WAIT,
    OPEN_LOGIN_REQUEST_WAIT,
    OPEN_ACCOUNT_INFO_REQUEST_WAIT,
    OPEN_FOLDER_LIST_WAIT,
    OPEN_FILE_LIST_WAIT,
    OPEN_HANDSHAKE_COMPLETED_WAIT,
    ESTABLISHED,
    CLOSED;

}
