stages:
  - test

variables:
  GIT_DEPTH: "1"
  ANT_OPTS: "-Xmx4g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"

test-Windows:
  stage: test
  resource_group: tests-Windows
  tags:
    - Windows
  script:
    - powershell -Command "Get-Process java -ErrorAction SilentlyContinue | Stop-Process -Force; Write-Host 'Old Java processes killed (if any)'"
    - powershell -Command "if (-not (Test-Path apache-ant-1.10.14)) { Invoke-WebRequest -UseBasicParsing -Uri 'https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.14-bin.zip' -OutFile ant.zip; Expand-Archive -Force ant.zip -DestinationPath . }"
    - apache-ant-1.10.14\bin\ant -lib lib/junit5 -lib apache-ant-1.10.14\lib run-tests
  artifacts:
    reports:
      junit: test-reports/raw/TEST-*.xml
    paths:
      - test-reports/*
    when: always
