stages:
  - test

test-Linux:
  stage: test
  tags:
    - Linux
    - Tests
  script:
    - pkill -f java || true
    - ant run-tests
  artifacts:
    reports:
      junit: test-reports/raw/TEST-*.xml
    paths:
      - test-reports/*

test-macOS:
  stage: test
  tags:
    - macOS
    - Tests
  script:
    - pkill -f java || true
    - ant run-tests
  artifacts:
    reports:
      junit: test-reports/raw/TEST-*.xml
    paths:
      - test-reports/*

test-Windows:
  stage: test
  tags:
    - Windows
    - Tests
  script:
    - powershell -Command "Get-Process java -ErrorAction SilentlyContinue | Stop-Process -Force; Write-Host 'Old Java processes killed (if any)'"
    - ant run-tests
  artifacts:
    reports:
      junit: test-reports/raw/TEST-*.xml
    paths:
      - test-reports/*