/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dal33t_powerfolder_util_os_Win32_WinUtils */

#ifndef _Included_de_dal33t_powerfolder_util_os_Win32_WinUtils
#define _Included_de_dal33t_powerfolder_util_os_Win32_WinUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef de_dal33t_powerfolder_util_os_Win32_WinUtils_CSIDL_COMMON_STARTUP
#define de_dal33t_powerfolder_util_os_Win32_WinUtils_CSIDL_COMMON_STARTUP 24L
#undef de_dal33t_powerfolder_util_os_Win32_WinUtils_CSIDL_STARTUP
#define de_dal33t_powerfolder_util_os_Win32_WinUtils_CSIDL_STARTUP 7L
/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_WinUtils
 * Method:    getSystemFolderPath
 * Signature: (IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dal33t_powerfolder_util_os_Win32_WinUtils_getSystemFolderPath
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_WinUtils
 * Method:    createLink
 * Signature: (Lde/dal33t/powerfolder/util/os/Win32/ShellLink;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dal33t_powerfolder_util_os_Win32_WinUtils_createLink
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_WinUtils
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_dal33t_powerfolder_util_os_Win32_WinUtils_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
