/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl */

#ifndef _Included_de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl
#define _Included_de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl
 * Method:    delete
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl_delete__Ljava_lang_String_2ZZ
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl
 * Method:    delete
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl_delete__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl
 * Method:    delete
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dal33t_powerfolder_util_os_Win32_RecycleDeleteImpl_delete__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
