/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dal33t_powerfolder_util_os_Win32_NetworkHelperImpl */

#ifndef _Included_de_dal33t_powerfolder_util_os_Win32_NetworkHelperImpl
#define _Included_de_dal33t_powerfolder_util_os_Win32_NetworkHelperImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dal33t_powerfolder_util_os_Win32_NetworkHelperImpl
 * Method:    getInterfaceAddresses
 * Signature: ()Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_de_dal33t_powerfolder_util_os_Win32_NetworkHelperImpl_getInterfaceAddresses
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
